### ISSUE TITLE
Support explicitly closing a connection

### ISSUE THREAD

**Issue by jraymakers** [duckdb/duckdb-node-neo#55]
The explicit `close` method got removed when automatic memory management was [added](https://github.com/duckdb/duckdb-node-neo/pull/43). But it can be useful to be able to explicitly close a connection.

A challenge is preventing the automatic memory management from double-freeing the connection after it is explicitly closed. To do this, we'll likely need to change the connection External to be a wrapper around the underlying connection pointer, so the underlying pointer can be cleared when it is explicitly freed.

**Comment by freakynit** [comment]
+1 for this. 

When a developer knows for sure they don't need the connection anymore, allow them to close it. 
Automated stuff is nice, but it shouldn't take away the `explicit` ability.

**Comment by recoye** [comment]
+1 for this.

**Comment by jraymakers** [comment]
This has been implemented in 1.1.3-alpha.8. Happy holidays! 🎉
