### ISSUE TITLE
darwin x64 support

### ISSUE THREAD

**Issue by salomartin** [duckdb/duckdb-node-neo#58]
It builds and runs just fine with a few lines of configuration added. Would you be open to supporting it and / or accept a pull request?

**Comment by jraymakers** [comment]
I've considered adding this, but I wasn't sure how many people would use it. You're right it should be straightforward. I've got other priorities right now, but if you want to submit a PR I'll be happy to work with you to get it in.

**Comment by jraymakers** [comment]
I went ahead and added Darwin x64 support (in version 1.1.3-alpha.7). I was working on Linux arm64 support (which was more tricky), so also adding Darwin x64 support was straightforward.

If you try it out, please let me know if it works for you or not. @salomartin
