### ISSUE TITLE
The problem of closing the connection

### ISSUE THREAD

**Issue by ussoft2011** [duckdb/duckdb-node-neo#71]
How should I close the connection? I couldn't find the close method. Please help me, thank you.

const instance = await DuckDBInstance.create(backPath, {
            threads: '4'
});
const connection = await instance.connect();

**Comment by jraymakers** [comment]
Duplicate of #55.

**Comment by jraymakers** [comment]
For this use case, I think it'll work better to `DETACH` the database before you delete it. According to DuckDB's [documentation](https://duckdb.org/docs/sql/statements/attach#detach), closing a connection won't fully disassociate DuckDB from any attached databases.
